"""Typed API errors so partner code can branch on stable codes rather than localized messages."""

from anis_partners.errors._codes import HTTP_STATUS, RETRY_GUIDANCE, RETRYABLE_CODES, ErrorCode, parse_error_code
from anis_partners.errors.anis_api_error import (
    AnisApiError,
    AuthorizationError,
    DependencyUnavailableError,
    EnrollmentRefusedError,
    IdempotencyConflictError,
    InsufficientBalanceError,
    InvalidCredentialsError,
    LimitExceededError,
    MalformedResponseError,
    OrderRefusalOutcome,
    OutOfStockError,
    PriceChangedError,
    RateLimitedError,
    ReplayDetectedError,
    ResourceNotFoundError,
    ValidationFailedError,
    create_api_error,
    outcome_of,
    parse_retry_after,
    refused_at_the_door,
)
from anis_partners.errors.base import AnisPartnersError, KeyDocumentUnavailableError

__all__ = [
    "HTTP_STATUS",
    "RETRYABLE_CODES",
    "RETRY_GUIDANCE",
    "AnisApiError",
    "AnisPartnersError",
    "AuthorizationError",
    "DependencyUnavailableError",
    "EnrollmentRefusedError",
    "ErrorCode",
    "IdempotencyConflictError",
    "InsufficientBalanceError",
    "InvalidCredentialsError",
    "KeyDocumentUnavailableError",
    "LimitExceededError",
    "MalformedResponseError",
    "OrderRefusalOutcome",
    "OutOfStockError",
    "PriceChangedError",
    "RateLimitedError",
    "ReplayDetectedError",
    "ResourceNotFoundError",
    "ValidationFailedError",
    "create_api_error",
    "outcome_of",
    "parse_error_code",
    "parse_retry_after",
    "refused_at_the_door",
]
